name: Update Algolia index

on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build pages
      run: hugo --minify
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Cache Dependencies
      uses: actions/cache@v2.1.6
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Node dependencies
      run: npm ci
    - name: Update Algolia index
      env:
        ALGOLIA_APP_ID: MFXX0N7AVC
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_INDEX_NAME: 'losloslos'
        ALGOLIA_INDEX_FILE: './public/index.json'
      run: npm run algolia
