name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build pages
      run: |
        hugo --minify
    - name: Deploy to GitHuub pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install atomic-algolia
      run: |
        sudo npm i -g atomic-algolia
    - name: Update Algolia index
      env:
        ALGOLIA_APP_ID: MFXX0N7AVC
        ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        ALGOLIA_INDEX_NAME: 'losloslos'
        ALGOLIA_INDEX_FILE: './public/index.json'
      run: |
        atomic-algolia
