name: Check Markdown links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
  # Run every Monday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'no'
        config-file: '.github/workflows/mlc_config.json'
        base-branch: main
        check-modified-files-only: 'yes'
