name: github pages

on: [push, pull_request]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    # Fetch all git history
    - name: Restore last modified time
      run: "git ls-files -z | while read -d '' path; do touch -d \"$(git log -1 --format=\"@%ct\" \"$path\")\" \"$path\"; done"
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Cache Dependencies
      uses: actions/cache@v2.1.5
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Build website
      run: npm ci --only=production && npm run build
    - name: Deploy to GH pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
