# https://github.com/peaceiris/actions-gh-pages

name: Test

on:
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  test:
    name: Test website
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'

    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.11.2'

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm ci --production
    - run: npm run build
